
[build]
  command = "npm run build"
  publish = "dist"
  edge_functions = "netlify/edge-functions"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/hoa"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/earning-set"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/boosting-set"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/laying-set"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/prestige-set"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/virtue-laying"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/optimal-set"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/error"
  to = "/index.html"
  status = 200

